In [31]:
import numpy as np


mat1D = np.array([1, 2, 3, 4, 5, 6, 7, 8,10,11,12])
mat2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10,11,12]])
mat2D10 = mat2D * 10

In [16]:
print(f"Matriks 1d:\n{mat1D}")
print(f"Matriks 1d ke 7:\n{mat1D[7]}")
print(f"Matriks 1d x 10:\n{mat1D * 10}")
print(f"Matriks 1d ke 7:\n{mat1D[7] * 5}")


Matriks 1d:
[1 2 3 4 5 6 7 8]
Matriks 1d ke 7:
8
Matriks 1d x 10:
[10 20 30 40 50 60 70 80]
Matriks 1d ke 7:
40


In [28]:
print(f"Matriks 2d:\n{mat2D}")
print(f"Matriks 2d x 10:\n{mat2D * 10}")
print(f"Matriks 1d ke 7:\n{mat2D[0]}")
print(mat2D10[0][2])

Matriks 2d:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks 2d x 10:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Matriks 1d ke 7:
[1 2 3]
30


In [30]:
print(mat1D.shape)
print(mat2D.shape)

(8,)
(3, 3)


In [33]:
print(mat1D.size)
print(mat2D.size)

11
12


In [51]:
mZero = np.zeros((3,3))
mone = np.ones((3000,3000))
mfull = np.full((4, 4), 7)  
midentity = np.eye((4))
mrandow = np.random.rand(5,5)
mrandow2 = np.random.rand(2)

randow3 = np.random.randint(10, 100, size=5)

print(mfull)
print(mone)
print(mZero)
print(midentity)
print(mrandow)
print(mrandow2)
print(randow3)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.55592746 0.6539074  0.03495886 0.24086018 0.87174144]
 [0.29998138 0.03605231 0.8877295  0.74963913 0.89391164]
 [0.08993124 0.30329833 0.20257077 0.58526044 0.38356313]
 [0.96018574 0.366452   0.09618809 0.2212526  0.13203915]
 [0.4658618  0.31740143 0.11338904 0.89096956 0.17531272]]
[0.23439631 0.03675032]
[71 96 63 22 74]


In [56]:
data= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ms = data.reshape((9,1))
mf  = data.flatten()

print(data)
print(ms)
print(mf)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [63]:
x = np.array([1,2,3,4])
y = np.array ([2,5,7,9])

r1 = np.dot(x,y)
r2 = np.add(x,y)

print(r1)
print(r2)
print(y.min())
print(y.max())
print(y.mean())
print(y.sum())
print(y.std())


69
[ 3  7 10 13]
2
9
5.75
23
2.5860201081971503


In [71]:
nilai = np.array ([100,90,80,50,60,70,90])

jmllulus = nilai[nilai>50]

print(jmllulus)
print(jmllulus.size)
print(nilai.size-jmllulus.size)



[100  90  80  60  70  90]
6
1


In [ ]:
#buatlah 1000 data costumer cc, yang akan di gunakan untuk produksi atau klafikasi yaitu usia, gender transaksi pembayaran
 

In [97]:
import numpy as np
import pandas as pd

jmldata = 1000
gender = np.random.choice(["L", "P"], size=jmldata)
transaksi = np.random.randint(0, 51, size=jmldata)
bayar = np.random.choice(["buruk", "sedang", "baik"], size=jmldata)
usia = np.random.randint(12, 61, size=jmldata)

df = pd.DataFrame({
    'usia': usia,
    'gender': gender,
    'pembayaran': bayar,
    'transaksi': transaksi
})

print(df)
print(df.info())
print(df.head())
df.to_csv("players.csv")

print(df['usia'].max())
print(df['usia'].min())
jmLL = df[df['gender']=='L']
print(jmLL.size/4)
print(jmLL['gender'].size)

     usia gender pembayaran  transaksi
0      59      P     sedang         21
1      41      P     sedang         26
2      33      P       baik          0
3      27      P     sedang         35
4      56      P       baik          5
..    ...    ...        ...        ...
995    23      P      buruk         41
996    59      L     sedang         39
997    59      L       baik          1
998    15      L     sedang         27
999    36      L       baik         26

[1000 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   usia        1000 non-null   int32 
 1   gender      1000 non-null   object
 2   pembayaran  1000 non-null   object
 3   transaksi   1000 non-null   int32 
dtypes: int32(2), object(2)
memory usage: 23.6+ KB
None
   usia gender pembayaran  transaksi
0    59      P     sedang         21
1    41      P     sedang       